### ISSUE TITLE
TypeError: Ref.__init__() got an unexpected keyword argument 'model_type'

### ISSUE THREAD

**Issue by neldivad** [GreenDelta/data#17]
`PS C:\Users\david\OneDrive\Desktop\Programming\greendelta-data\scripts> python .\build_libs.py
Traceback (most recent call last):
  File "C:\Users\david\OneDrive\Desktop\Programming\greendelta-data\scripts\build_libs.py", line 269, in <module>
    main()
  File "C:\Users\david\OneDrive\Desktop\Programming\greendelta-data\scripts\build_libs.py", line 77, in main 
    data = model.RefData.read(model.RefDataSet.ALL)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\OneDrive\Desktop\Programming\greendelta-data\scripts\model.py", line 32, in read      
    _units_into(data)
  File "C:\Users\david\OneDrive\Desktop\Programming\greendelta-data\scripts\model.py", line 99, in _units_into
    prop.unit_group = _ref_of(group)
                      ^^^^^^^^^^^^^^
  File "C:\Users\david\OneDrive\Desktop\Programming\greendelta-data\scripts\model.py", line 349, in _ref_of  
    return lca.Ref(
           ^^^^^^^^
TypeError: Ref.__init__() got an unexpected keyword argument 'model_type'`

Repo doesnt work right out of the box. `olca-schema` seems to be incompatible with `scripts/build_libs.py`

On the side note, is there a better way to write in the values of each flow? Is so hard to find the names for anything when everything is abstracted as its uuid.

**Comment by neldivad** [comment]
I fixed it by updating requirements.txt 

```
olca-schema==0.0.8 <<< set to equals instead of greater than
scipy>=1.9.3
```

**Comment by msrocka** [comment]
Thanks, I merged your pull request. I do not understand your question:

> On the side note, is there a better way to write in the values of each flow? Is so hard to find the names for anything when everything is abstracted as its uuid.

Yes, everything is identified by an uuid, but also everything has a name attached to that uuid, so not sure what you mean.
